
### registeruser
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "username":"Daniel",
    "email": "kakinyidk@gmail.com",
    "password": "12345678"
}

###loginUser
POST http://localhost:5000/users/login
Content-Type: application/json

{
    
    "email":"gamesmy177@gmail.com",
    "password":"1234567"  
}
###
GET http://localhost:5000/users/check
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkRhbiIsImVtYWlsIjoiZ2FtZXNteTE3N0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInN0YXR1cyI6ImFjdGl2ZSIsImlzX3NlbnQiOiJ5ZXMiLCJpYXQiOjE2NjM1NzI4MjgsImV4cCI6MTY2MzU3NDgyOH0.366cKcSCLszsCIRdA5SfonPML0laVZ5R0mudFQCzOJc
###

GET http://localhost:5000/users/homepage
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6IkRhbiIsImVtYWlsIjoiZ2FtZXNteTE3N0BnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsInN0YXR1cyI6ImFjdGl2ZSIsImlzX3NlbnQiOiJ5ZXMiLCJpYXQiOjE2NjM1NzI4MjgsImV4cCI6MTY2MzU3NDgyOH0.366cKcSCLszsCIRdA5SfonPML0laVZ5R0mudFQCzOJc

### get all users
GET http://localhost:5000/users/all
Content-Type: application/json


### adding parcel
POST http://localhost:5000/parcels/add
Content-Type: application/json

{
    "senderemail":"dan@gmail.com",
    "receiveremail": "mercy@gmail.com",
    "parcel_desc":"fragile",
    "fromLoc": "Othaya",
    "toLoc":"Nairobi",
    "status":"dispatched",
    "weight":"60",
    "price":"9000"
    
}

### get all parcels 
GET http://localhost:5000/parcels/all
Content-Type: application/json

### deleting parcel
DELETE  http://localhost:5000/parcels/deleteparcel/3076
Content-Type: application/json

### update when parcel is sent
PUT  http://localhost:5000/parcels/sent/3078
Content-Type: application/json

{
    "senderemail":"justus@gmail.com",
    "receiveremail": "morris@gmail.com",
    "parcel_desc":"fragile",
    "fromLoc": "Othaya",
    "toLoc":"Nairobi",
    "status":"dispatched",
    "weight":"60",
    "price":"800"

}

### update when parcel is delievered

PUT  http://localhost:5000/parcels/delivered/3077
Content-Type: application/json

{
    "senderemail":"justus@gmail.com",
    "receiveremail": "morris@gmail.com",
    "parcel_desc":"fragile",
    "fromLoc": "Othaya",
    "toLoc":"Nairobi",
    "status":"dispatched",
    "weight":"60",
    "price":"800"

}

### updating parcel
PUT  http://localhost:5000/parcels/update/3078
Content-Type: application/json

{
    "senderemail":"muthonijustus@gmail.com",
    "receiveremail": "irungumorris@gmail.com",
    "parcel_desc":"fragile",
    "fromLoc": "Othaya",
    "toLoc":"Nairobi",
    "status":"dispatched",
    "weight":"60",
    "price":"9000"
    
}



